# Generated by Django 2.2.11 on 2020-03-15 20:08

import author.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20200315_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=author.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='author.Passion'),
        ),
    ]
